'use strict';
const $ = (s, root = document) => root.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = {certs: [], me: null, bookmarks: [], category: '전체', query: '', domestic: '', limit: 18};
let routeVersion = 0;
async function api(path, options = {}) {
  const response = await fetch('/api' + path, {credentials:'same-origin', ...options, headers:{'Content-Type':'application/json', ...options.headers}});
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : '입력값을 확인해 주세요.');
  return data;
}
const send = (path, body, method='POST') => api(path, {method, body:JSON.stringify(body)});
function toast(message) { const el=$('#toast'); el.textContent=message; el.style.display='block'; clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.style.display='none',4000); }
function modal(html) { $('#modal-body').innerHTML=html; if(!$('#modal').open) $('#modal').showModal(); }
$('#close-modal').onclick=()=>$('#modal').close();
function account() {
  $('#account').innerHTML=state.me ? `<a href="#mine">${esc(state.me.name)} 님</a>${state.me.admin?'<a href="#admin">관리</a>':''}<button class="outline" id="logout">로그아웃</button>` : '<button id="login" class="outline">로그인 / 가입</button>';
  if($('#login')) $('#login').onclick=()=>auth(false);
  if($('#logout')) $('#logout').onclick=async()=>{try{await send('/auth/logout',{});state.me=null;state.bookmarks=[];account();route();}catch(e){toast(e.message);}};
}
function auth(register=false) {
  modal(`<form class="form" id="auth-form"><span class="eyebrow">WELCOME TO INFRAPASS</span><h2>${register?'함께 준비해요':'다시 만나 반가워요'}</h2>${register?'<label>닉네임<input name="name" minlength="2" maxlength="40" required autocomplete="nickname"></label>':''}<label>이메일<input name="email" type="email" required autocomplete="email" maxlength="190"></label><label>비밀번호<input name="password" type="password" minlength="10" maxlength="128" required autocomplete="${register?'new-password':'current-password'}" placeholder="10자 이상"></label><p class="error" role="alert"></p><button>${register?'가입하기':'로그인'}</button><button type="button" class="soft" id="switch-auth">${register?'이미 계정이 있어요':'처음 오셨나요? 회원가입'}</button></form>`);
  $('#switch-auth').onclick=()=>auth(!register);
  $('#auth-form').onsubmit=async e=>{e.preventDefault();const f=e.target;const b=$('button',f);b.disabled=true;try{state.me=await send('/auth/'+(register?'register':'login'),Object.fromEntries(new FormData(f)));state.bookmarks=await api('/bookmarks');$('#modal').close();account();route();}catch(err){$('.error',f).textContent=err.message;}finally{b.disabled=false;}};
}
function card(c) {return `<a class="card" href="#cert/${encodeURIComponent(c.slug)}"><div class="card-top"><span class="provider-icon">${esc(c.provider.slice(0,3))}</span><span class="badge">${esc(c.category)}</span></div><p>${esc(c.provider)}</p><h3>${esc(c.name)}</h3><p>${esc(c.domestic?'국내':'글로벌')} 자격 · 공식 정보와 수험 경험</p><div class="card-bottom"><span>${c.verified_at?'정보 확인 '+esc(c.verified_at):'상세 정보 검수 중'}</span><span>살펴보기 ↗</span></div></a>`;}
function catalog(mine=false) {
  $('#main').innerHTML=`${mine?'<div class="section-title"><div><span class="eyebrow">MY LEARNING</span><h2>내가 준비하는 다음 단계</h2></div></div>':`<section class="hero"><div><span class="eyebrow">BUILD YOUR NEXT CHAPTER</span><h1>다음 커리어로 가는 길,<br>나에게 맞는 자격증부터.</h1><p>인프라부터 보안까지. 흩어진 시험 정보와<br>먼저 도전한 사람들의 경험을 한곳에서 만나보세요.</p></div><div class="hero-art" aria-hidden="true"><div class="orbit"></div><div class="pass"><small>YOUR NEXT DESTINATION</small><b>Next level.</b><div class="stamp">↗</div><hr><small>LEARN · CONNECT · GROW</small></div></div></section>`}<div class="section-title"><h2>${mine?'관심 자격증':'자격증 탐색'}</h2><span class="muted">공식 출처와 함께, 차근차근</span></div><div class="search"><input id="search" aria-label="자격증 검색" placeholder="자격증 이름, 발급기관, 정처기, SAA로 검색" value="${esc(state.query)}"><select id="domestic" aria-label="국내 해외 구분"><option value="">국내 · 글로벌 전체</option value="domestic">국내 자격</option><option value="global">글로벌 자격</option></select></div><div class="chips">${['전체',...new Set(state.certs.map(c=>c.category))].map(x=>`<button data-category="${esc(x)}" class="${state.category===x?'active':''}">${esc(x)}</button>`).join('')}</div><div class="layout"><section><p id="result-count" class="muted"></p><div class="grid" id="results"></div><button class="outline more" id="more">더 보기</button></section><aside class="sidebar"><section class="side"><span class="eyebrow">FIND YOUR PATH</span><h3>어디서부터 시작할까요?</h3><a href="#roadmap"><span>01</span>클라우드 엔지니어 →</a><a href="#roadmap"><span>02</span>네트워크 엔지니어 →</a><a href="#roadmap"><span>03</span>보안 전문가 →</a></section><section class="side green"><span class="eyebrow">LEARN BY DOING</span><h3>읽고, 직접 구성해 보세요.</h3><p>Linux부터 웹 서버까지.<br>개념을 경험으로 바꾸는 실습 가이드.</p><a href="#labs">실습 가이드 둘러보기 ↗</a></section><section class="side"><h3>함께 만드는 정확한 정보</h3><p>잘못된 정보나 변경 사항을 발견했나요? 자격증 상세에서 수정 제보를 보내주세요.</p><p>검수되지 않은 일정과 비용은 임의로 표시하지 않습니다.</p></section></aside></div>`;
  $('#domestic').value=state.domestic;
  const refresh=()=>{const q=state.query.toLowerCase().trim();const rows=state.certs.filter(c=>(!mine||state.bookmarks.includes(c.slug))&&(state.category==='전체'||c.category===state.category)&&(!state.domestic||c.domestic===(state.domestic==='domestic'))&&[c.name,c.provider,c.aliases].join(' ').toLowerCase().includes(q));$('#result-count').innerHTML=`총 <span class="metric">${rows.length}</span>개의 자격증`;$('#results').innerHTML=rows.slice(0,state.limit).map(card).join('')||'<div class="empty"><h3>아직 표시할 자격증이 없어요.</h3>검색 조건을 바꾸거나 관심 자격증을 저장해 보세요.</div>';$('#more').hidden=rows.length<=state.limit;};
  $('#search').oninput=e=>{state.query=e.target.value;state.limit=18;refresh();};$('#domestic').onchange=e=>{state.domestic=e.target.value;state.limit=18;refresh();};document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;state.limit=18;catalog(mine);});$('#more').onclick=()=>{state.limit+=18;refresh();};refresh();
}
const section=(title,body,label='편집 가이드')=>`<section class="article"><small>${esc(label)}</small><h2>${esc(title)}</h2><p>${esc(body)}</p></section>`;
async function detail(slug) {
  const c=state.certs.find(x=>x.slug===slug);if(!c){$('#main').innerHTML='<div class="empty">자격증을 찾을 수 없습니다.</div>';return;}
  $('#main').innerHTML=`<div class="breadcrumb"><a href="#">자격증 탐색</a> / ${esc(c.category)} / ${esc(c.name)}</div><section class="detail-head"><span class="badge">${esc(c.category)}</span> <span class="muted">${esc(c.provider)}</span><h1>${esc(c.name)}</h1><p>${esc(c.summary)}</p><div class="actions"><button id="bookmark" class="soft">${state.bookmarks.includes(slug)?'✓ 관심 자격증':'＋ 관심 자격증'}</button><a class="button" href="${esc(c.source)}" target="_blank" rel="noopener noreferrer">공식 정보 확인 ↗</a><button id="report" class="outline">정보 수정 제보</button></div><div class="notice">${c.verified_at?'마지막 정보 확인: '+esc(c.verified_at):'카탈로그 등록 단계입니다. 시험별 상세 정보는 검수 중이며 접수 전 공식 안내를 확인하세요.'}</div></section><div class="tabs">${['개요','시험·취득','학습·실습','후기','질문'].map((t,i)=>`<button data-tab="${i}" class="${i===0?'active':''}">${t}</button>`).join('')}</div><div id="detail-content"></div>`;
  $('#bookmark').onclick=async()=>{if(!state.me){auth();return;}try{const saved=state.bookmarks.includes(slug);await api('/bookmarks/'+slug,{method:saved?'DELETE':'PUT'});state.bookmarks=await api('/bookmarks');$('#bookmark').textContent=saved?'＋ 관심 자격증':'✓ 관심 자격증';}catch(e){toast(e.message);}};
  $('#report').onclick=()=>{if(!state.me){auth();return;}modal('<form id="report-form" class="form"><h2>정보 수정 제보</h2><label>변경 내용과 확인할 공식 출처<textarea name="body" required minlength="2" maxlength="5000"></textarea></label><p class="error"></p><button>제보 보내기</button></form>');$('#report-form').onsubmit=async e=>{e.preventDefault();try{await send('/certificates/'+slug+'/reports',Object.fromEntries(new FormData(e.target)));$('#modal').close();toast('제보가 접수되었습니다.');}catch(err){$('.error',e.target).textContent=err.message;}};};
  const tab=async i=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',+b.dataset.tab===i));const target=$('#detail-content');if(i===0)target.innerHTML=section('이런 분께 추천해요',c.audience)+section('취득까지의 흐름',c.process,'공식 요건 확인이 필요한 준비 안내');if(i===1)target.innerHTML=section('시험과 응시 정보',c.exam,c.verified_at?'공식 출처 기반 정보':'공식 상세 검수 대기')+section('취득 후 유지·갱신',c.renewal,'공식 정책 확인')+section('시험 일정',c.events.length?c.events.map(e=>e.date+' · '+e.title).join('\n'):'확인된 회차 일정이 없습니다. 상시 예약형 시험은 공식 접수처에서 좌석을 확인하세요.','공식 일정');if(i===2)target.innerHTML=section('학습 순서와 자료',c.study)+`<section class="article"><small>공통 인프라 역량</small><h2>개념을 직접 확인하는 실습</h2><p>Linux·네트워크·서버 운영 기초를 직접 구성해 보세요. 벤더 고유 서비스는 해당 공식 실습 환경을 이용하세요.</p><a class="button" href="#labs">실습 가이드 보기 ↗</a></section>`;if(i>=3){target.innerHTML='<p class="loading">글을 불러오는 중입니다.</p>';try{const rows=await api('/posts?certificate='+encodeURIComponent(slug)+'&kind='+encodeURIComponent(i===3?'후기':'질문'));if(!target.isConnected||!$(`[data-tab="${i}"].active`))return;target.innerHTML=`<div class="section-title"><h2>${i===3?'준비 경험을 나눠 주세요':'함께 해결해요'}</h2><button id="write">글 작성</button></div>${postList(rows)}`;$('#write').onclick=()=>write(slug,i===3?'후기':'질문');bindPosts(rows);}catch(e){target.innerHTML=section('불러오지 못했습니다',e.message);}}};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(+b.dataset.tab));tab(0);
}
function postList(rows){return rows.length?rows.map(p=>`<button class="post" data-post="${p.id}" style="width:100%;text-align:left;color:inherit;border-radius:0"><span class="badge">${esc(p.kind)}</span> <small>${esc(state.certs.find(c=>c.slug===p.certificate)?.name||p.certificate)}</small><h3>${esc(p.title)}</h3><p class="muted">${esc(p.body.slice(0,110))}</p><small>${esc(p.author)} · ${new Date(p.created).toLocaleDateString('ko-KR')}</small></button>`).join(''):'<div class="empty"><h3>첫 번째 경험을 기다리고 있어요.</h3>질문이나 준비 경험을 나눠 주세요. 실제 시험 문항은 공유하지 않습니다.</div>';}
function bindPosts(rows){document.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>openPost(rows.find(p=>p.id===+b.dataset.post)));}
async function openPost(p){modal(`<article class="article"><span class="badge">${esc(p.kind)}</span><h2>${esc(p.title)}</h2><small>${esc(p.author)} · 사용자 경험</small><p>${esc(p.body)}</p>${Object.entries(p.details).filter(([,v])=>v).map(([k,v])=>`<p><b>${esc(k)}</b> · ${esc(v)}</p>`).join('')}</article><h3>댓글</h3><div id="comments">불러오는 중…</div><form id="comment-form" class="form"><label>답변·댓글<textarea name="body" required minlength="2" maxlength="5000"></textarea></label><p class="error"></p><button>댓글 등록</button></form>`);async function refresh(){const rows=await api('/posts/'+p.id+'/comments');if($('#comments'))$('#comments').innerHTML=rows.map(c=>`<div class="article"><small>${esc(c.author)}</small><p>${esc(c.body)}</p></div>`).join('')||'<p class="muted">아직 댓글이 없습니다.</p>'; }try{await refresh();}catch(e){$('#comments').textContent=e.message;}$('#comment-form').onsubmit=async e=>{e.preventDefault();if(!state.me){auth();return;}try{await send('/posts/'+p.id+'/comments',Object.fromEntries(new FormData(e.target)));e.target.reset();await refresh();}catch(err){$('.error',e.target).textContent=err.message;}};}
function write(slug='',kind='후기') {if(!state.me){auth();return;}const requestId=crypto.randomUUID();modal(`<form id="post-form" class="form"><h2>경험과 궁금증을 나눠 주세요</h2><div class="row"><label>자격증<select name="certificate">${state.certs.map(c=>`<option value="${esc(c.slug)}" ${c.slug===slug?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>글 종류<select name="kind">${['후기','질문','공부 기록','스터디'].map(k=>`<option ${k===kind?'selected':''}>${k}</option>`).join('')}</select></label></div><label>제목<input name="title" required minlength="2" maxlength="160"></label><label>내용<textarea name="body" required minlength="10" maxlength="15000" placeholder="도움이 된 방법, 막혔던 부분을 나눠 주세요."></textarea></label><details><summary>후기 추가 정보 (선택)</summary><div class="row">${['응시일','시험 버전','결과','실무 경험','준비 기간','주당 학습 시간','학습 자료','총 비용','체감 난이도'].map(k=>`<label>${k}<input name="detail:${k}" maxlength="500"></label>`).join('')}</div></details><small class="muted">합격 여부는 본인 작성 정보입니다. 실제 시험 문항·덤프와 개인정보는 올리지 마세요.</small><p class="error" role="alert"></p><button>등록하기</button></form>`);$('#post-form').onsubmit=async e=>{e.preventDefault();const form=e.target;const data=Object.fromEntries(new FormData(form));const details={};Object.keys(data).filter(k=>k.startsWith('detail:')).forEach(k=>{details[k.slice(7)]=data[k];delete data[k];});const b=$('button',form);b.disabled=true;try{await send('/posts',{...data,details,request_id:requestId});$('#modal').close();toast('글이 등록되었습니다.');location.hash='community';route();}catch(err){$('.error',form).textContent=err.message;}finally{b.disabled=false;}};}
async function community(){const version=routeVersion;$('#main').innerHTML='<div class="section-title"><div><span class="eyebrow">LEARN TOGETHER</span><h2>혼자 준비하지 않아도 괜찮아요.</h2></div><button id="write">글 작성</button></div><p class="muted">질문, 응시 후기, 공부 기록과 스터디 모집을 함께 나눕니다.</p><div id="posts"></div><button id="next-posts" class="outline more">더 보기</button>';$('#write').onclick=()=>write();let all=[];async function more(){const b=$('#next-posts');b.disabled=true;try{const rows=await api('/posts?offset='+all.length);if(version!==routeVersion)return;all=all.concat(rows);$('#posts').innerHTML=postList(all);bindPosts(all);b.hidden=rows.length<30;}catch(e){toast(e.message);}finally{b.disabled=false;}}$('#next-posts').onclick=more;await more();}
function schedule(){const rows=state.certs.flatMap(c=>c.events.map(e=>({...e,c}))).sort((a,b)=>a.date.localeCompare(b.date));$('#main').innerHTML='<span class="eyebrow">EXAM CALENDAR</span><h1>시험 일정을 놓치지 않도록</h1><p class="muted">검수한 공식 회차 일정만 제공합니다. 상시 시험은 접수처에서 예약 가능한 날짜를 확인하세요.</p>'+ (rows.length?rows.map(e=>`<a class="post" href="#cert/${esc(e.c.slug)}"><span class="badge">${esc(e.date)}</span><h3>${esc(e.c.name)}</h3>${esc(e.title)}</a>`).join(''):'<div class="empty"><h3>확인된 시험 일정을 준비하고 있습니다.</h3>자격증 상세의 공식 정보 링크에서 최신 접수 일정을 확인해 주세요.</div>');}
function roadmap(){$('#main').innerHTML='<span class="eyebrow">FIND YOUR PATH</span><h1>목표에서 시작하는 학습 경로</h1><p class="muted">편집 추천 경로입니다. 공식 선수 자격이나 취득 의무 순서를 뜻하지 않습니다.</p>'+[['클라우드 엔지니어','Linux·네트워크 기초','Cloud Practitioner / Cloud Digital Leader','SAA / Associate Cloud Engineer','운영·보안 심화'],['네트워크 엔지니어','TCP/IP·서브넷','네트워크관리사 / CCNA','라우팅·장애 분석','CCNP 분야별 심화'],['보안 엔지니어','Linux·네트워크 기초','CC / 정보보안기사 응시 요건 확인','보안 관제·취약점 분석','직무에 맞는 전문 자격'],['개인정보보호 담당자','개인정보 처리 흐름','CPPG 학습 범위 확인','보호조치·관리 체계','CIPM / CIPT 등 직무별 심화']].map(([title,...steps])=>`<section class="article"><h2>${title}</h2><div class="path">${steps.map((s,i)=>`<span>${i+1}. ${s}</span>`).join('')}</div></section>`).join('');}
const guides=[{id:'linux',title:'첫 Linux 서버, 안전하게 시작하기',tag:'Linux · 기초',steps:['IXcloud에서 Ubuntu VM과 SSH 키를 준비합니다. 관리용 공인 IP 접근은 본인 IP로 제한합니다.','SSH 키를 사용해 접속하고 whoami, uname -a, df -h로 사용자·커널·디스크를 확인합니다.','일반 사용자를 만들고 sudo 권한을 설정합니다. 새 사용자 접속을 확인한 뒤 root 직접 로그인을 제한합니다.','systemctl --failed와 journalctl로 서비스 상태와 로그를 살펴봅니다.','실습 후 VM·볼륨·공인 IP 등 과금 자원을 확인하고 불필요한 자원을 정리합니다.']},{id:'web',title:'Nginx로 첫 웹 페이지 올리기',tag:'WEB · 기초',steps:['Ubuntu VM에서 sudo apt update, sudo apt install nginx로 Nginx를 설치합니다.','/var/www/html/index.html에 본인의 테스트 페이지를 작성합니다.','sudo nginx -t로 설정을 검사하고 sudo systemctl reload nginx로 적용합니다.','curl -I http://127.0.0.1로 응답을 확인한 뒤 허용한 클라이언트에서 접속합니다.','외부 공개 시 HTTPS를 구성합니다. 실습 종료 후 인스턴스와 연결 자원을 정리합니다.']},{id:'network',title:'서브넷과 접근 제어 이해하기',tag:'네트워크 · 기초',steps:['서로 다른 서브넷에 실습 VM을 배치하고 각 사설 IP와 라우팅을 기록합니다.','한 VM에 테스트 웹 서버를 설치하고 다른 VM에서 curl로 접속을 확인합니다.','소스 IP·대상 포트를 제한하는 보안 규칙을 적용합니다.','허용한 소스의 성공과 차단한 소스의 실패를 각각 확인합니다. SSH 접근을 먼저 유지하세요.','보안 규칙·라우트·테스트 결과를 정리한 뒤 실습 자원을 회수합니다.']}];
function labs(id){const g=guides.find(g=>g.id===id);$('#main').innerHTML=g?`<div class="breadcrumb"><a href="#labs">실습 가이드</a> / ${esc(g.title)}</div><section class="article guide"><span class="eyebrow">LEARN BY DOING</span><h1>${esc(g.title)}</h1><p>IXcloud 환경 기준의 자율 실습 가이드입니다. 현재 콘솔의 메뉴와 지원 기능을 확인하며 진행하세요.</p><ol>${g.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="notice">실습에는 이용 요금이 발생할 수 있습니다. 자원 생성 전 요금을 확인하고 종료 후 남은 자원을 점검하세요.</div><div class="actions"><a class="button" href="https://www.kinx.net/service/cloud/" target="_blank" rel="noopener noreferrer">IXcloud 알아보기 ↗</a><a class="button" href="https://m.kinx.net/service/price/" target="_blank" rel="noopener noreferrer">요금 확인 ↗</a></div></section>`:'<span class="eyebrow">LEARN BY DOING</span><h1>아는 것을, 할 수 있는 것으로.</h1><p class="muted">공통 인프라 기술을 직접 구성하는 가이드입니다. AWS·GCP 고유 서비스의 공식 실습을 대체하지 않습니다.</p><div class="grid">'+guides.map(g=>`<a class="card" href="#labs/${g.id}"><span class="badge">${g.tag}</span><h3>${g.title}</h3><p>단계별 가이드 · IXcloud 환경 기준</p><div class="card-bottom">실습 가이드 읽기 ↗</div></a>`).join('')+'</div>';}
async function adminPage(){if(!state.me?.admin){$('#main').innerHTML=section('관리자 전용','관리자 계정으로 로그인하세요.');return;}$('#main').innerHTML='<h1>정보 검수</h1><section class="article"><form id="edit-form" class="form"><label>자격증<select id="edit-cert">'+state.certs.map(c=>`<option value="${c.slug}">${esc(c.name)}</option>`).join('')+'</select></label><label>수정할 정보 (JSON)<textarea id="edit-data" rows="16" spellcheck="false"></textarea></label><p class="muted">공식 출처를 검수한 항목만 수정하고 verified_at에 확인일을 기록하세요. events는 date(YYYY-MM-DD), title 배열입니다. 변경 전 정보는 감사 이력에 보관됩니다.</p><p class="error"></p><button>검수 정보 저장</button></form></section><h2>수정 제보</h2><div id="reports"></div>';function selectCert(){const c=state.certs.find(c=>c.slug===$('#edit-cert').value);const keys=['summary','audience','process','study','exam','renewal','verified_at','status','events'];$('#edit-data').value=JSON.stringify(Object.fromEntries(keys.map(k=>[k,c[k]])),null,2);}$('#edit-cert').onchange=selectCert;selectCert();$('#edit-form').onsubmit=async e=>{e.preventDefault();try{const slug=$('#edit-cert').value;const c=await send('/admin/certificates/'+slug,JSON.parse($('#edit-data').value),'PUT');state.certs=state.certs.map(old=>old.slug===slug?c:old);toast('저장했습니다.');}catch(err){$('.error',e.target).textContent=err.message;}};const rows=await api('/admin/reports');if(!$('#reports'))return;$('#reports').innerHTML=rows.map(r=>`<section class="article"><small>${esc(r.certificate)}</small><p>${esc(r.body)}</p>${r.resolved?'<span class="badge">처리 완료</span>':`<button data-resolve="${r.id}">처리 완료</button>`}</section>`).join('')||'<p>접수된 제보가 없습니다.</p>';document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=async()=>{try{await api('/admin/reports/'+b.dataset.resolve,{method:'PATCH'});adminPage();}catch(e){toast(e.message);}});}
async function route(){routeVersion++;const [page,id]=(location.hash.slice(1)||'catalog').split('/');document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page||(page==='cert'&&a.dataset.nav==='catalog')));window.scrollTo(0,0);try{if(page==='cert')return detail(decodeURIComponent(id||''));if(page==='community')return await community();if(page==='schedule')return schedule();if(page==='roadmap')return roadmap();if(page==='labs')return labs(id);if(page==='admin')return await adminPage();if(page==='mine'){if(!state.me){auth();$('#main').innerHTML=section('나의 학습','로그인 후 관심 자격증을 모아볼 수 있습니다.');return;}return catalog(true);}if(page==='about'){$('#main').innerHTML=section('InfraPass 소개','인프라·보안 자격증의 공식 정보와 학습 경험을 연결합니다. InfraPass는 KINX가 운영하며, 각 자격증 발급기관의 공식 사이트는 아닙니다. IXcloud 실습 가이드는 공통 인프라 역량을 익히기 위한 선택지입니다.');return;}if(page==='policy'){$('#main').innerHTML=section('커뮤니티 원칙','출처와 경험을 구분해 주세요. 실제 시험 문항·덤프, 타인의 개인정보, 광고성 도배와 비방은 게시할 수 없습니다. 합격·불합격 모두 소중한 학습 경험입니다. 수정이 필요한 자격 정보는 상세 페이지에서 제보할 수 있습니다.');return;}if(page==='privacy'){$('#main').innerHTML=section('개인정보 안내 · 공개 전 검토 필요','서비스는 이메일, 닉네임, 비밀번호 해시와 로그인 세션을 저장합니다. 작성한 글·댓글·제보와 관심 자격증도 저장합니다. 비밀번호 원문은 저장하지 않습니다. 운영자 연락처, 보유기간과 계정 삭제 절차를 확정한 정식 개인정보처리방침은 공개 운영 전에 게시해야 합니다.');return;}catalog();}catch(e){$('#main').innerHTML=section('잠시 연결이 원활하지 않습니다',e.message);}}
async function start(){try{state.certs=await api('/certificates');try{state.me=await api('/me');state.bookmarks=await api('/bookmarks');}catch{state.me=null;}account();route();}catch(e){$('#main').innerHTML=section('정보를 불러오지 못했습니다',e.message)+'<button id="retry">다시 시도</button>';$('#retry').onclick=start;account();}}
window.addEventListener('hashchange',route);start();
